### ISSUE TITLE
Oracle 10 and 13 misses platforms

### ISSUE THREAD

**Issue by marchof** [foojay2020/discoapi#10]
Missing foojay packages for oracle[10]: [linux-x64, solaris-sparcv9, macos-x64, windows-x64]
    Missing foojay packages for oracle[13]: [linux-x64, macos-x64, windows-x64]

Probably this is because they moved the download pages to the archive:

* https://www.oracle.com/java/technologies/java-archive-javase10-downloads.html
* https://www.oracle.com/java/technologies/javase/jdk13-archive-downloads.html

**Comment by HanSolo** [comment]
Will be fixed with next deployment

**Comment by marchof** [comment]
Re-tested: ✅

Thx!
