### ISSUE TITLE
Add AdoptOpenJDK Upstream Builds?

### ISSUE THREAD

**Issue by marchof** [foojay2020/discoapi#11]
Hi, does it make sense to add packages from AdoptOpenJDK Upstream Builds?

* https://adoptopenjdk.net/upstream.html?variant=openjdk8
* https://adoptopenjdk.net/upstream.html?variant=openjdk11

**Comment by HanSolo** [comment]
Hmm…will take a look at it, thx for the hint 👍🏻

**Comment by HanSolo** [comment]
We use these already but take them from their github releases.

**Comment by marchof** [comment]
What is the packageid?

**Comment by HanSolo** [comment]
For example for oracle_openjdk,  version 8.0.282 for linux it is: 71beda9a27266bce53f6991373e44a25

**Comment by marchof** [comment]
Maybe I don't get the idea of AdopOpenJDK Upstream Builds. You say they are basically the same as oracle_openjdk?

**Comment by HanSolo** [comment]
Afaik they build it for RedHat, they do also builds of Dragonwell.

**Comment by marchof** [comment]
Ok, maybe I ignore this package for now until I found out what it actually is. I think the package listing came in through a pull request. I'll try to ask the submitter.

Thx!
