### ISSUE TITLE
Wrong architecture for some Zulu windows downloads?

### ISSUE THREAD

**Issue by marchof** [foojay2020/discoapi#12]
Please see result of this query:

https://api.foojay.io/disco/v1.0/packages?distro=zulu&version=6&operating_system=windows&architecture=x86

Download files like 'zulu1.6.0_56-6.6.0.1-x86lx64.zip' are reported as 'x86'. I would rather expect it to be x64.

**Comment by HanSolo** [comment]
Indeed I was not aware of the x86lx64 and x86lx32 naming...will fix it...thx for the heads up

**Comment by HanSolo** [comment]
Will be fixed with next deployment

**Comment by marchof** [comment]
Retest: ✅
