### ISSUE TITLE
Wrong lib_c_type for oracle_open_jdk

### ISSUE THREAD

**Issue by marchof** [foojay2020/discoapi#13]
The following packages should be "musl":

	{
		"id": "81458b8ed126fcbb00064748ec872dee",
		"archive_type": "tar.gz",
		"distribution": "oracle_open_jdk",
		"major_version": 17,
		"java_version": "17-ea.10",
		"distribution_version": "17-ea.10",
		"latest_build_available": true,
		"release_status": "ea",
		"term_of_support": "lts",
		"operating_system": "linux",
		"lib_c_type": "glibc",
		"architecture": "x64",
		"package_type": "jdk",
		"javafx_bundled": false,
		"directly_downloadable": true,
		"filename": "openjdk-17-ea+10_linux-x64-musl_bin.tar.gz",
		"ephemeral_id": "33381458b8ed126fcbb00064748ec872dee1614192036"
	}

	{
		"id": "673165e6fea8bdb382cdcfe4c1699185",
		"archive_type": "tar.gz",
		"distribution": "oracle_open_jdk",
		"major_version": 17,
		"java_version": "17-ea",
		"distribution_version": "17",
		"latest_build_available": false,
		"release_status": "ea",
		"term_of_support": "lts",
		"operating_system": "linux",
		"lib_c_type": "glibc",
		"architecture": "x64",
		"package_type": "jdk",
		"javafx_bundled": false,
		"directly_downloadable": true,
		"filename": "openjdk-17-ea+5_linux-x64-musl_bin.tar.gz",
		"ephemeral_id": "387673165e6fea8bdb382cdcfe4c16991851614192036"
	}

**Comment by HanSolo** [comment]
Fixed in dev branch (commit: 49403710ce06d63524ce437e36b5b4aad8bcf625). Will come with next deployment.

**Comment by marchof** [comment]
Retest: `lib_c_type` is now reported correctly ✅
