### ISSUE TITLE
Error Codes

### ISSUE THREAD

**Issue by khmarbaise** [foojay2020/discoapi#18]
In cases if combinations of search criterias which would result in an empty result I think it should result into an error code instead of an empty json array.

**Comment by jeschu** [comment]
Search criteria filter items - if remaining list of filtered items it is an empty result, not an error - just my opinion

**Comment by HanSolo** [comment]
Added a json msg like
{
  "info":"No package found"
}

**Comment by marchof** [comment]
Hallo @khmarbaise looks like your proposal has been implemented. I'm not a client side JavaScript expert. Did you have any idea in mind how to use the new API properly? Now my client code looks like this 🙀:

    if (Array.isArray(response.data)) {
      this.packages = response.data;
    } else {
      this.packages = [];
    }

**Comment by marchof** [comment]
Hi, I think this issue has been resolved long time ago and with the v2.0 API there is a proper machine readable schema for situations with and without result items.

So I think this issues can be closed as fixed. In general as a API user it would be very valuable if the issues' status here would reflect the current status of the API.

**Comment by HanSolo** [comment]
I agree, sorry for being a bit lazy...
