### ISSUE TITLE
Packages for sap_machine miss some platforms

### ISSUE THREAD

**Issue by marchof** [foojay2020/discoapi#24]
The following API call only returns packages for `macos-x64` and `linux-ppc64`:

https://api.foojay.io/disco/v1.0/packages?distro=sap_machine&version=17-ea&latest=overall

In fact there are also packages available for `linux-x64`, `linux-ppc64le`and `windows-x64` which are nor reported by the disco API:

https://github.com/SAP/SapMachine/releases/tag/sapmachine-17%2B16

**Comment by HanSolo** [comment]
Yep, saw that too and fixed it already. It will come with the next deployment.

**Comment by marchof** [comment]
Great! Any chance that you comment on the tickets once they are fixed in production? I'm happy to re-test.

**Comment by HanSolo** [comment]
Yep will do 👍🏻

**Comment by marchof** [comment]
Just retested: Looks like package list is complete now.
