### ISSUE TITLE
Distribution oracle / version 15 is not found any more

### ISSUE THREAD

**Issue by marchof** [foojay2020/discoapi#30]
**Reproducer**

https://api.foojay.io/disco/v1.0/packages?distro=oracle&version=15&latest=per_version

**Analysis**

Probably this is because the download site has been moved to https://www.oracle.com/java/technologies/javase/jdk15-archive-downloads.html

**Comment by HanSolo** [comment]
Yep...changed that, so it should be working again soon (cache will be cleaned up every 2h). Doing a new deployment at the moment so it might take a bit longer.

**Comment by marchof** [comment]
Ok, fixed!

Can you please comment on the other issues if they are fixed by the deployment?
