### ISSUE TITLE
Feature: JetBrains Runtime variant

### ISSUE THREAD

**Issue by sideeffffect** [foojay2020/discoapi#39]
JetBrains is maintaining an excellent variant of Java11 and Java8 with fixes for desktop and GUI application to help with Subpixel Anti-Aliasing, enhanced font rendering on Linux, HiDPI support, ligatures among few other fixes.

confluence.jetbrains.com/display/JBR/JetBrains+Runtime

related issue: https://github.com/sdkman/sdkman-db-migrations/issues/465

**Comment by HanSolo** [comment]
So I'm currently adding the JetBrains jbrsdk 11.0.5 - 11.0.11, you think that's enough for the start?

**Comment by HanSolo** [comment]
Ok so you can hopefully get those sdks within this week...just keep an eye on this issue, I will close it as soon as the sdks are available. And thank's for the heads up...👍🏻

**Comment by sideeffffect** [comment]
Awesome, thank you! :rocket:

**Comment by HanSolo** [comment]
my pleasure :)

**Comment by HanSolo** [comment]
Implemented with commit #3662ee3fae2bbd231a583fd6187171dcee31b192
