### ISSUE TITLE
package endpoint returns empty string for architecture

### ISSUE THREAD

**Issue by marchof** [foojay2020/discoapi#40]
Our sync with javaalmanac.io started failing a couple of days ago due to empty `architecture` values in the response to this request:

https://api.foojay.io/disco/v2.0/packages?version=17-ea&distro=oracle_open_jdk&latest=available

**Comment by geertjanw** [comment]
Gerrit will check and get back to you ASAP.

**Comment by HanSolo** [comment]
Yep I also saw that and it is already fixed in the codebase and will go to production soon.

**Comment by HanSolo** [comment]
Should be fixed with latest deployment.

**Comment by marchof** [comment]
Confirmed. Thanks!
